---
- name: Instal apache2 and start apache2 with handler
  hosts: webserver
  become: yes
  gather_facts: yes
  vars:
    pkg_name: apache2
  tasks:
    - name: Install apache2
      apt:
        name: "{{pkg_name}}"
        state: present

    - name: Copy index.html
      copy:
        content: "Hello From HTML"
        dest: /var/www/html/index.html
      notify: Restart apache2
  handlers:
    - name: Restart apache2
      service:
        name: "{{pkg_name}}"
        state: restarted



